fix: read GOROOT at runtime, but fallback to compile-time
OpenPeeDeeP/depguard pull request #48
Opened 2023-06-01 22:53 UTC by adamdecaf

Fixes: https://github.com/OpenPeeDeeP/depguard/issues/46
More Info: https://github.com/golangci/golangci-lint/issues/3862

2023-06-01 22:58 UTC, ldez commented
This PR doesn't fix the problem https://github.com/golangci/golangci-lint/issues/3862#issuecomment-1572893272

2023-06-01 23:17 UTC, adamdecaf commented
I've updated this PR to include more strategies from https://github.com/golangci/golangci-lint/issues/3862#issuecomment-1572900443

2023-06-01 23:34 UTC, ldez requested changes

2023-06-01 23:34 UTC, ldez commented on internal/utils/variables.go
> +	root := path.Join(goroot, "src")
```suggestion
	root := path.Join(findGOROOT(), "src")
```

2023-06-01 23:34 UTC, ldez commented on internal/utils/variables.go
> +func findGOROOT() string {
```suggestion
// code borrowed from https://github.com/golang/tools/blob/86c93e8732cce300d0270bce23117456ce92bb17/cmd/godoc/goroot.go#L15-L30
func findGOROOT() string {
```

2023-06-01 23:37 UTC, ldez requested changes

2023-06-01 23:37 UTC, ldez commented on internal/utils/variables.go
> +	return filepath.Clean(goroot)
```suggestion
	if env := os.Getenv("GOROOT"); env != "" {
		return filepath.Clean(env)
	}
	def := filepath.Clean(runtime.GOROOT())
	if runtime.Compiler == "gccgo" {
		// gccgo has no real GOROOT, and it certainly doesn't
		// depend on the executable's location.
		return def
	}
	out, err := exec.Command("go", "env", "GOROOT").Output()
	if err != nil {
		return def
	}
	return strings.TrimSpace(string(out))
```

2023-06-02 00:54 UTC, gandarez submitted a review, later dismissed

2023-06-02 12:47 UTC, adamdecaf commented
Updated from codereview, thanks.

2023-06-02 15:19 UTC, dixonwille approved these changes

2023-06-02 15:19 UTC, dixonwille commented
Thanks you so much for this!

2023-06-02 15:19 UTC, merged